[build]
  command = "next build"
  publish = "out"

# Remove or comment out the Next.js plugin as it's not needed for static exports
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
